heat_template_version: 2021-04-16
description: >
  Ubuntu server deployment

parameters:
  allowed_address_pairs:
    type: json
    default:
      - {ip_address: 10.0.0.0/8}
      - {ip_address: 172.16.0.0/12}
      - {ip_address: 192.168.0.0/16}
  flavor:
    type: string
    default: c3.8c16m10d
  floating_network:
    type: string
    default: external
  image:
    type: string
    default: Ubuntu Noble Server 2024-10-04
  key_name:
    type: string
    default: dean_taylor_sydney_edu_au
  metadata:
    type: json
  network:
    type: string
    default: er01
  os_project:
    type: string
    default: er01
  os_provider:
    type: string
    default: nci
  security_groups:
    type: json
    default: ["er01 ssh"]
  volume_size:
    type: number
    default: 10
  volume_type:
    type: string
    default: Nirin2_General
    #default: Nirin2_Transaction

resources:
  server:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: flavor}
      key_name: {get_param: key_name}
      metadata: {get_param: metadata}
      name:
        str_replace:
          template: ip-${HOST_IP}.${OS_PROVIDER}-${OS_PROJECT}.sydney.edu.au
          params:
            ${HOST_IP}: {list_join: ['-', {str_split: ['.', {get_attr: [serverPort, fixed_ips, 0, ip_address]}]}]}
            ${OS_PROJECT}: {get_param: os_project}
            ${OS_PROVIDER}: {get_param: os_provider}
      image: {get_param: image}
      block_device_mapping_v2:
      - boot_index: -1
        delete_on_termination: true
        volume_id: {get_resource: microk8sVolume}
      networks:
      - floating_ip: {get_resource: externalIp}
        port: {get_resource: serverPort}
      tags: []
      user_data:
        str_replace:
          template: |
            #cloud-config
            fs_setup:
            - label: microk8s
              filesystem: xfs
              device: ${VOLUME_PATH}
            hostname: ${HOSTNAME}
            fqdn: ${HOSTNAME}.${DOMAIN}
            keyboard:
              layout: us
            locale: en_AU.utf8
            mounts:
            -
              - ${VOLUME_PATH}
              - /var/snap/microk8s/common
            package_update: true
            package_upgrade: true
            package_reboot_if_required: true
            timezone: Australia/Sydney
            write_files:
            - path: /etc/sysctl.d/99-forwarding.conf
              content: |
                net.ipv4.ip_forward=1
                net.ipv6.conf.all.forwarding=1
            - path: /etc/systemd/journald.conf.d/syslog.conf
              content: |
                [Journal]
                ForwardToSyslog=no
          params:
            ${DOMAIN}:
              str_replace:
                template: ${OS_PROVIDER}-${OS_PROJECT}.sydney.edu.au
                params:
                  ${OS_PROJECT}: {get_param: os_project}
                  ${OS_PROVIDER}: {get_param: os_provider}
            ${HOSTNAME}:
              str_replace:
                template: ip-${HOST_IP}
                params:
                  ${HOST_IP}: {list_join: ['-', {str_split: ['.', {get_attr: [serverPort, fixed_ips, 0, ip_address]}]}]}
            ${VOLUME_PATH}:
              str_replace:
                template: /dev/disk/by-id/virtio-${VOLUME_ID}
                params:
                  ${VOLUME_ID}:
                    yaql:
                      expression: $.data.volume_id.substring(0,20)
                      data:
                        volume_id: {get_resource: microk8sVolume}
      user_data_format: RAW
      user_data_update_policy: IGNORE

  microk8sVolume:
    type: OS::Cinder::Volume
    properties:
      size: {get_param: volume_size}
      volume_type: {get_param: volume_type}

  externalIp:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: {get_param: floating_network}

  serverPort:
    type: OS::Neutron::Port
    properties:
      network: {get_param: network}
      admin_state_up: true
      allowed_address_pairs: {get_param: allowed_address_pairs}
      port_security_enabled: true
      security_groups: {get_param: security_groups}
