---
AWSTemplateFormatVersion: "2010-09-09"
Description: VRD lab
Parameters:
  AvailabilityZones:
    Description: "Availability zone list"
    Type: "List<AWS::EC2::AvailabilityZone::Name>"
    Default: "ap-southeast-2a,ap-southeast-2b,ap-southeast-2c"
  ASGDesiredCapacity:
    Type: Number
    Description: "Auto Scale Group desired capacity (i.e., Number of VM instances)"
    Default: 0
  LaunchTemplateName:
    Type: String
  LaunchTemplateVersion:
    Type: Number

Conditions: {}

Outputs: {}

Resources:
  AutoScaleGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones: !Ref AvailabilityZones
      DesiredCapacity: !Ref ASGDesiredCapacity
      LaunchTemplate:
        LaunchTemplateName: !Ref LaunchTemplateName
        Version: !Ref LaunchTemplateVersion
      MaxSize: 24
      MinSize: 0
